---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      component: mongo
  replicas: 1
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
  - port: 27017