---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      component: mongo
  replicas: 1
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
  - port: 27017